#Import Libraries

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

#Import Data

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/DhruvBhirud/datasets/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [6]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


#Missing Value

In [8]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [9]:
df[df['Review Text']==""]=np.NaN

In [10]:
df['Review Text'].fillna("No Review",inplace=True)

In [11]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [12]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

#Define y and X

In [13]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [14]:
X = df['Review Text']

In [15]:
y = df['Rating']

In [16]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

#Train Test Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y,random_state=12529)

#Get Feature Text Conversion to Tokens

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3),stop_words='english',max_features=5000)

In [21]:
X_train = cv.fit_transform(X_train)

In [22]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [23]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
X_test = cv.fit_transform(X_test)

In [25]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yesterday store',
       'yoga pants', 'zipper little'], dtype=object)

In [26]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#Get Model Train

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
model = MultinomialNB()

In [29]:
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [30]:
y_pred = model.predict(X_test)

In [31]:
y_pred

array([1., 5., 5., ..., 4., 5., 3.])

#Get Probability of Each Predict Class

In [32]:
model.predict_proba(X_test)

array([[2.65835746e-01, 2.24213110e-01, 2.57868252e-01, 2.54507807e-02,
        2.26632112e-01],
       [7.48941348e-02, 1.81350717e-03, 7.19264566e-02, 7.46604242e-03,
        8.43899859e-01],
       [1.91308368e-01, 1.22753446e-01, 2.73195950e-01, 3.68931260e-02,
        3.75849110e-01],
       ...,
       [3.62904194e-02, 4.98127434e-02, 2.54313714e-01, 5.45540703e-01,
        1.14042420e-01],
       [1.85901424e-01, 2.51203883e-02, 7.20021397e-02, 1.59201343e-01,
        5.57774705e-01],
       [2.30681738e-01, 7.03793194e-02, 6.52835845e-01, 4.55968623e-02,
        5.06235509e-04]])

#Get Model Evaluation

In [33]:
from sklearn.metrics import confusion_matrix, classification_report

In [34]:
print(confusion_matrix(y_test, y_pred))

[[  26   15   38   39  135]
 [  61   40   69   77  223]
 [ 111   71  124  144  411]
 [ 169  119  205  292  738]
 [ 497  259  411  566 2206]]


In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.10      0.05       253
         2.0       0.08      0.09      0.08       470
         3.0       0.15      0.14      0.15       861
         4.0       0.26      0.19      0.22      1523
         5.0       0.59      0.56      0.58      3939

    accuracy                           0.38      7046
   macro avg       0.22      0.22      0.21      7046
weighted avg       0.41      0.38      0.40      7046



#Recategories Rating as Poor 0 and Good 1

In [36]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

Rerating as 1,2,3 as 0 and 4,5 as 1

In [37]:
df.replace({'Rating': {1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [38]:
y=df['Rating']

In [39]:
X=df['Review Text']

#Train Test Split

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.7,random_state=12529)

#Get Feature Text Conversion to Tokens

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
cv = CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [44]:
X_train = cv.fit_transform(X_train)

In [45]:
X_test = cv.fit_transform(X_test)

#Get Model ReTrain

In [46]:
from sklearn.naive_bayes import MultinomialNB

In [47]:
model = MultinomialNB()

In [48]:
model.fit(X_train, y_train)

MultinomialNB()

#Get Model Prediction

In [49]:
y_pred = model.predict(X_test)

In [50]:
y_pred

array([0., 1., 1., ..., 1., 1., 1.])

#Get Model Evaluation

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
print(confusion_matrix(y_test,y_pred))

[[ 362 1226]
 [ 964 4494]]


In [53]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.27      0.23      0.25      1588
         1.0       0.79      0.82      0.80      5458

    accuracy                           0.69      7046
   macro avg       0.53      0.53      0.53      7046
weighted avg       0.67      0.69      0.68      7046

